theme: jekyll-theme-slate
title: Welcome to the home of Stephen Williams!
description: Bookmark this page and keep an eye out for updates somewhere around the time I'm not taking compilers and operating systems in the same semester!
