theme: jekyll-theme-slate
title: Hi! I'm Stephen, nice to meet you!
description: Bookmark this page and keep an eye out for updates somewhere around the time I'm not taking compilers and operating systems in the same semester!
